version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    # Altere o caminho para apontar para o novo arquivo .env.dev
    env_file:
      - ./envs/.env.dev
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Altere o caminho aqui também
    env_file:
      - ./envs/.env.dev
    ports:
      - "5432:5432"

volumes:
  postgres_data: