version: '3.8'

services:
  # Serviço do Back-end (API Python)
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000"      
    volumes:
      - ./backend/app:/app  
                          
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/quadrafacil_db
    depends_on:
      - db               

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quadrafacil_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: